name: Automated Security

on:
  push:
    branches: [ "main", "master", "develop", "staging" ]
  pull_request:
    branches: [ "main", "master", "develop", "staging" ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Snyk Code Scan
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=medium
        continue-on-error: true

      - name: Snyk Dependency Scan
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=medium
        continue-on-error: true

      - name: Snyk IaC Scan
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: iac test
          args: --severity-threshold=high
        continue-on-error: true
