name: Secret Scan (gitleaks)

on:
  push:
    branches: ["master","main","staging","develop","ft-hw-onboarding"]
  pull_request:
    branches: ["master","main","staging","develop","ft-hw-onboarding"]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v8
        with:
          # Points to the config file you added
          config: .gitleaks.toml
