name: Secret Scan (Snyk)
on:
  push:
    branches: [ "main", "master", "develop", "staging" ]
  pull_request:
    branches: [ "main", "master", "develop", "staging" ]

jobs:
  snyk-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Snyk Secrets Scan
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=low --scan-all-unmanaged
        continue-on-error: true
